DROP TABLE ASISTENCIA_ESTUDIANTE CASCADE CONSTRAINTS;
DROP TABLE ASISTENCIA_AULA CASCADE CONSTRAINTS;
DROP TABLE HISTORICO_AULA_ESTUDIANTE CASCADE CONSTRAINTS;
DROP TABLE HISTORICO_HORARIO_AULA CASCADE CONSTRAINTS;
DROP TABLE NOTA_ESTUDIANTE CASCADE CONSTRAINTS;
DROP TABLE ESTUDIANTE CASCADE CONSTRAINTS;
DROP TABLE ASIGNACION_TUTOR CASCADE CONSTRAINTS;
DROP TABLE MOTIVO_INASISTENCIA CASCADE CONSTRAINTS;
DROP TABLE SEMANA CASCADE CONSTRAINTS;
DROP TABLE FESTIVO CASCADE CONSTRAINTS;
DROP TABLE HORARIO CASCADE CONSTRAINTS;
DROP TABLE AULA CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE PERSONA CASCADE CONSTRAINTS;
DROP TABLE SEDE CASCADE CONSTRAINTS;
DROP TABLE INSTITUCION CASCADE CONSTRAINTS;
DROP TABLE PERIODO CASCADE CONSTRAINTS;
DROP TABLE COMPONENTE CASCADE CONSTRAINTS;



CREATE TABLE INSTITUCION (
  id_institucion    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_inst       VARCHAR2(200) NOT NULL UNIQUE,
  jornada           VARCHAR2(20) NOT NULL,
  dir_principal     VARCHAR2(400) NOT NULL
);


CREATE TABLE SEDE (
  id_institucion    NUMBER NOT NULL,
  id_sede           NUMBER NOT NULL,
  direccion         VARCHAR2(400) NOT NULL UNIQUE,
  es_principal      CHAR(1) NOT NULL DEFAULT 'N',
  CONSTRAINT pk_sede PRIMARY KEY (id_institucion, id_sede),
  CONSTRAINT fk_sede_institucion FOREIGN KEY (id_institucion) REFERENCES INSTITUCION(id_institucion)
);


CREATE TABLE PERSONA (
  id_persona        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_doc          VARCHAR2(20) NOT NULL,
  num_documento     VARCHAR2(50) UNIQUE NOT NULL,
  nombre            VARCHAR2(250) NOT NULL,
  telefono          VARCHAR2(50),
  correo            VARCHAR2(200) UNIQUE NOT NULL,
  rol               VARCHAR2(20) NOT NULL
);


CREATE TABLE USUARIO (
  nombre_user       VARCHAR2(100) PRIMARY KEY,
  contrasena        VARCHAR2(200) NOT NULL,
  id_persona        NUMBER UNIQUE,
  CONSTRAINT fk_usuario_persona FOREIGN KEY (id_persona) REFERENCES PERSONA(id_persona)
);


CREATE TABLE AULA (
  id_aula           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_institucion    NUMBER NOT NULL,
  id_sede           NUMBER NOT NULL,
  grado             VARCHAR2(10) NOT NULL,
  id_tutor_aula     NUMBER,
  CONSTRAINT fk_aula_sede FOREIGN KEY (id_institucion, id_sede) REFERENCES SEDE(id_institucion, id_sede),
  CONSTRAINT fk_aula_tutor FOREIGN KEY (id_tutor_aula) REFERENCES SEDE(ASIGNACION_TUTOR)
);


CREATE TABLE HORARIO (
  id_horario        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dia_semana        VARCHAR2(10),
  h_inicio          VARCHAR2(5),
  h_final           VARCHAR2(5),
  minutos_equiv     NUMBER DEFAULT 60,
  es_continuo       CHAR(1) DEFAULT 'S'
);


CREATE TABLE HISTORICO_HORARIO_AULA (
  id_hist_horario   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_aula           NUMBER NOT NULL,
  id_horario        NUMBER NOT NULL,
  fecha_inicio      DATE NOT NULL,
  fecha_fin         DATE,
  CONSTRAINT fk_hha_aula FOREIGN KEY (id_aula) REFERENCES AULA(id_aula),
  CONSTRAINT fk_hha_horario FOREIGN KEY (id_horario) REFERENCES HORARIO(id_horario)
);


CREATE TABLE ASIGNACION_TUTOR (
  id_tutor_aula     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_persona        NUMBER NOT NULL,
  fecha_inicio      DATE NOT NULL,
  fecha_fin         DATE,
  motivo_cambio     VARCHAR2(400),
  CONSTRAINT fk_at_persona FOREIGN KEY (id_persona) REFERENCES PERSONA(id_persona)
);


CREATE TABLE ESTUDIANTE (
  id_estudiante     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_documento    VARCHAR2(20) NOT NULL,
  num_documento     VARCHAR2(50) UNIQUE NOT NULL,
  nombres           VARCHAR2(250) NOT NULL,
  apellidos         VARCHAR2(250) NOT NULL,
  telefono          VARCHAR2(50),
  fecha_nacimiento  DATE,
  correo            VARCHAR2(200) UNIQUE NOT NULL,
  score_entrada     NUMBER,
  score_salida      NUMBER
);


CREATE TABLE HISTORICO_AULA_ESTUDIANTE (
  id_hist_aula_est  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estudiante     NUMBER NOT NULL,
  id_aula           NUMBER NOT NULL,
  fecha_inicio      DATE NOT NULL,
  fecha_fin         DATE,
  CONSTRAINT fk_hae_est FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTE(id_estudiante),
  CONSTRAINT fk_hae_aula FOREIGN KEY (id_aula) REFERENCES AULA(id_aula)
);


CREATE TABLE MOTIVO_INASISTENCIA (
  id_motivo         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion       VARCHAR2(400) NOT NULL
);


CREATE TABLE SEMANA (
  id_semana         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_semana     NUMBER NOT NULL,
  fecha_inicio      DATE NOT NULL,
  fecha_fin         DATE NOT NULL
);


CREATE TABLE FESTIVO (
  id_festivo        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha             DATE NOT NULL,
  descripcion       VARCHAR2(400) NOT NULL
);


CREATE TABLE ASISTENCIA_AULA (
  id_asist          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_aula           NUMBER NOT NULL,
  id_tutor_aula     NUMBER,
  id_horario        NUMBER,
  id_semana         NUMBER,
  fecha_clase       DATE NOT NULL,
  dictada           CHAR(1) DEFAULT 'N' NOT NULL,
  horas_dictadas    NUMBER DEFAULT 0 NOT NULL,
  reposicion        CHAR(1) DEFAULT 'N',
  fecha_reposicion  DATE,
  id_motivo         NUMBER,
  hora_inicio       VARCHAR2(5) NOT NULL,
  hora_fin          VARCHAR2(5) NOT NULL,
  corresponde_horario NUMBER(1),
  es_festivo        NUMBER(1),
  CONSTRAINT fk_aa_aula FOREIGN KEY (id_aula) REFERENCES AULA(id_aula),
  CONSTRAINT fk_aa_tutor FOREIGN KEY (id_tutor_aula) REFERENCES ASIGNACION_TUTOR(id_tutor_aula),
  CONSTRAINT fk_aa_horario FOREIGN KEY (id_horario) REFERENCES HORARIO(id_horario),
  CONSTRAINT fk_aa_semana FOREIGN KEY (id_semana) REFERENCES SEMANA(id_semana),
  CONSTRAINT fk_aa_motivo FOREIGN KEY (id_motivo) REFERENCES MOTIVO_INASISTENCIA(id_motivo)
);


CREATE TABLE ASISTENCIA_ESTUDIANTE (
  id_asist_est      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_asist          NUMBER NOT NULL,
  id_estudiante     NUMBER NOT NULL,
  asistio           CHAR(1) DEFAULT 'N',
  observacion       VARCHAR2(400),
  CONSTRAINT fk_ae_asistencia FOREIGN KEY (id_asist) REFERENCES ASISTENCIA_AULA(id_asist),
  CONSTRAINT fk_ae_estudiante FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTE(id_estudiante)
);


CREATE TABLE PERIODO (
  id_periodo        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre            VARCHAR2(100),
  fecha_inicio      DATE,
  fecha_fin         DATE
);


CREATE TABLE COMPONENTE (
  id_componente     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre            VARCHAR2(200),
  porcentaje        NUMBER,
  tipo_programa     VARCHAR2(200),
  id_periodo        NUMBER NOT NULL,
  CONSTRAINT fk_componente_periodo FOREIGN KEY (id_periodo) REFERENCES PERIODO(id_periodo)
);


CREATE TABLE NOTA_ESTUDIANTE (
  id_nota           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estudiante     NUMBER NOT NULL,
  id_componente     NUMBER NOT NULL,
  nota              NUMBER NOT NULL,
  CONSTRAINT fk_ne_est FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTE(id_estudiante),
  CONSTRAINT fk_ne_periodo FOREIGN KEY (id_periodo) REFERENCES PERIODO(id_periodo),
  CONSTRAINT fk_ne_componente FOREIGN KEY (id_componente) REFERENCES COMPONENTE(id_componente)
);
