-- DDL para GLOBALENGLISH (Oracle)
-- Usuario/schema esperado: GLOBALENGLISH

-- 1) Type defaults
-- Ajusta tamaños según necesidades reales
-- ---------------------------------------------------------

CREATE TABLE INSTITUCION (
  id_institucion    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_inst       VARCHAR2(200) NOT NULL,
  jornada           VARCHAR2(20), -- 'UNICA_MAÑANA', 'UNICA_TARDE', 'MIXTA'
  dir_principal     VARCHAR2(400)
);

-- Sede: entidad débil de Institucion -> PK compuesta (id_institucion, id_sede)
CREATE TABLE SEDE (
  id_institucion    NUMBER NOT NULL,
  id_sede           NUMBER NOT NULL, -- identificador local por institucion
  direccion         VARCHAR2(400),
  es_principal      CHAR(1) DEFAULT 'N',
  CONSTRAINT pk_sede PRIMARY KEY (id_institucion, id_sede),
  CONSTRAINT fk_sede_institucion FOREIGN KEY (id_institucion) REFERENCES INSTITUCION(id_institucion)
);

CREATE TABLE PERSONA (
  id_persona        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_doc          VARCHAR2(20),
  nombre            VARCHAR2(250), -- incluye apellidos
  telefono          VARCHAR2(50),
  correo            VARCHAR2(200),
  rol               VARCHAR2(20) -- 'TUTOR','ADMINISTRATIVO','ADMINISTRADOR'
);

CREATE TABLE USUARIO (
  nombre_user       VARCHAR2(100) PRIMARY KEY,
  contrasena        VARCHAR2(200) NOT NULL,
  id_persona        NUMBER,
  CONSTRAINT fk_usuario_persona FOREIGN KEY (id_persona) REFERENCES PERSONA(id_persona)
);

CREATE TABLE AULA (
  id_aula           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_institucion    NUMBER NOT NULL,
  id_sede           NUMBER NOT NULL,
  grado             VARCHAR2(10), -- '4','5','9','10'
  CONSTRAINT fk_aula_sede FOREIGN KEY (id_institucion, id_sede) REFERENCES SEDE(id_institucion, id_sede)
);

CREATE TABLE HORARIO (
  id_horario        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dia_semana        VARCHAR2(10), -- 'LUNES'..'DOMINGO'
  h_inicio          VARCHAR2(5),  -- 'HH24:MI'
  h_final           VARCHAR2(5),
  minutos_equiv     NUMBER DEFAULT 60, -- 40/45/50/55/60 equivalen a 1 hora
  es_continuo       CHAR(1) DEFAULT 'S'
);

-- Historico_horario_aula: relación entre Aula y Horario con vigencia
CREATE TABLE HISTORICO_HORARIO_AULA (
  id_hist_horario   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_aula           NUMBER NOT NULL,
  id_horario        NUMBER NOT NULL,
  fecha_inicio      DATE,
  fecha_fin         DATE,
  CONSTRAINT fk_hha_aula FOREIGN KEY (id_aula) REFERENCES AULA(id_aula),
  CONSTRAINT fk_hha_horario FOREIGN KEY (id_horario) REFERENCES HORARIO(id_horario)
);

-- Asignacion_Tutor: relacion N-M entre Persona (tutor) y Aula con historial
CREATE TABLE ASIGNACION_TUTOR (
  id_tutor_aula     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_persona        NUMBER NOT NULL,
  id_aula           NUMBER NOT NULL,
  fecha_inicio      DATE,
  fecha_fin         DATE,
  motivo_cambio     VARCHAR2(400),
  CONSTRAINT fk_at_persona FOREIGN KEY (id_persona) REFERENCES PERSONA(id_persona),
  CONSTRAINT fk_at_aula FOREIGN KEY (id_aula) REFERENCES AULA(id_aula)
);

CREATE TABLE ESTUDIANTE (
  id_estudiante     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_documento    VARCHAR2(20),
  num_documento     VARCHAR2(50),
  nombres           VARCHAR2(250),
  apellidos         VARCHAR2(250),
  telefono          VARCHAR2(50),
  fecha_nacimiento  DATE,
  correo            VARCHAR2(200),
  score_entrada     NUMBER,
  score_salida      NUMBER
);

CREATE TABLE HISTORICO_AULA_ESTUDIANTE (
  id_hist_aula_est  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estudiante     NUMBER NOT NULL,
  id_aula           NUMBER NOT NULL,
  fecha_inicio      DATE,
  fecha_fin         DATE,
  CONSTRAINT fk_hae_est FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTE(id_estudiante),
  CONSTRAINT fk_hae_aula FOREIGN KEY (id_aula) REFERENCES AULA(id_aula)
);

CREATE TABLE MOTIVO_INASISTENCIA (
  id_motivo         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion       VARCHAR2(400)
);

CREATE TABLE SEMANA (
  id_semana         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_semana     NUMBER,
  fecha_inicio      DATE,
  fecha_fin         DATE
);

CREATE TABLE FESTIVO (
  id_festivo        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha             DATE,
  descripcion       VARCHAR2(400)
);

CREATE TABLE ASISTENCIA_AULA (
  id_asist          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_aula           NUMBER NOT NULL,
  id_tutor_aula     NUMBER,           -- quien tomó la asistencia
  id_horario        NUMBER,           -- cada asistencia pertenece a un horario
  id_semana         NUMBER,
  fecha_clase       DATE,
  dictada           CHAR(1) DEFAULT 'N', -- 'S'/'N'
  horas_dictadas    NUMBER DEFAULT 0,    -- número de minutos/hora equivalente dictadas
  reposicion        CHAR(1) DEFAULT 'N',
  fecha_reposicion  DATE,
  id_motivo         NUMBER,
  CONSTRAINT fk_aa_aula FOREIGN KEY (id_aula) REFERENCES AULA(id_aula),
  CONSTRAINT fk_aa_tutor FOREIGN KEY (id_tutor_aula) REFERENCES ASIGNACION_TUTOR(id_tutor_aula),
  CONSTRAINT fk_aa_horario FOREIGN KEY (id_horario) REFERENCES HORARIO(id_horario),
  CONSTRAINT fk_aa_semana FOREIGN KEY (id_semana) REFERENCES SEMANA(id_semana),
  CONSTRAINT fk_aa_motivo FOREIGN KEY (id_motivo) REFERENCES MOTIVO_INASISTENCIA(id_motivo)
);

CREATE TABLE ASISTENCIA_ESTUDIANTE (
  id_asist_est      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_asist          NUMBER NOT NULL,
  id_estudiante     NUMBER NOT NULL,
  asistio           CHAR(1) DEFAULT 'N',
  observacion       VARCHAR2(400),
  CONSTRAINT fk_ae_asistencia FOREIGN KEY (id_asist) REFERENCES ASISTENCIA_AULA(id_asist),
  CONSTRAINT fk_ae_estudiante FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTE(id_estudiante)
);

CREATE TABLE PERIODO (
  id_periodo        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre            VARCHAR2(100),
  fecha_inicio      DATE,
  fecha_fin         DATE
);

CREATE TABLE COMPONENTE (
  id_componente     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre            VARCHAR2(200),
  porcentaje        NUMBER
);

CREATE TABLE NOTA_ESTUDIANTE (
  id_nota           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estudiante     NUMBER NOT NULL,
  id_periodo        NUMBER,
  id_componente     NUMBER,
  nota              NUMBER,
  CONSTRAINT fk_ne_est FOREIGN KEY (id_estudiante) REFERENCES ESTUDIANTE(id_estudiante),
  CONSTRAINT fk_ne_periodo FOREIGN KEY (id_periodo) REFERENCES PERIODO(id_periodo),
  CONSTRAINT fk_ne_componente FOREIGN KEY (id_componente) REFERENCES COMPONENTE(id_componente)
);
